language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install .[test]
  - pip install codecov

# command to run tests, TODO should we move this to a script?
script:
  - pytest 
  
after_success:
  - codecov
